text_extraction_task:
  agent: image_text_extractor
  description: >
    Extract all the text from the image and return only the text and nothing else."image_url": {image_path}. 
  expected_output: >
    All the text extracted from the image.

document_classification_task:
  agent: document_classifier
  description: >
    Classify the document based on the extracted text into one of these categories:
    - Invoice 
    - Delivery Note 
    - Reception Note 
    - Purchase Order
    - Unknown
    Look for key indicators and patterns in the text that identify the document type.
  expected_output: >
    A string containing the document classification category(document_type) and the full text extracted from the image(aggregated_output).


ocr_output_aggregation:
  agent: ocr_output_aggregator
  description: >
    Using the text extraction outputs from {llama_ocr_output}, {minicpm_ocr_output}, and the output from the text extraction task, analyze and reconcile differences to consolidate the information. 
    You can assume the output from the text extraction task is the most accurate.
    Produce a single, accurate extraction that retains key details from each model output.
  expected_output: >
    The final, aggregated text extraction, reflecting the most accurate information across all three model outputs.

