data_extractor:
  role: Senior Data Extractor
  goal: Extract specific data fields based on the document type.
  backstory: >
    You are an AI assistant tasked with extracting the following fields: {fields} from {aggregated_output}. 


